symon-ai/tap-s3-csv

- requirements.txt
https://varicent.atlassian.net/browse/WP-6903
follow up task for #5
> WP-6903: update requirements.txt

- CHANGELOG.md
- setup.py
- tap_s3_csv/__init__.py
- tap_s3_csv/conversion.py
- tap_s3_csv/s3.py
- tap_s3_csv/sync.py
- Increase the limit on the width of a field in the CSV files read by the tap [#47](https://github.com/singer-io/singer-encodings/pull/47)
modified the function to update the csv in the csv_iterator.py file
> WP-9041 merge latest change upstream

- setup.py
- tap_s3_csv/__init__.py
- tap_s3_csv/csv_iterator.py
- tap_s3_csv/dialect.py
WP-10259 CSV Import Performance
https://varicent.atlassian.net/browse/WP-10259
notes:
- added dialect detection code for running tap-csv imports
- for tap-csv imports using tap-s3-csv, tap config will not have external_id
> WP-10259 CSV Import Performance

- setup.py
- tap_s3_csv/conversion.py
jira: https://varicent.atlassian.net/browse/WP-10528
app pr: https://github.com/symon-ai/app/pull/7319
v1.3.10 should be created
> WP-10528: avoid throwing error when there are malformed rows

- setup.py
- tap_s3_csv/csv_iterator.py
https://varicent.atlassian.net/browse/WP-11429
Quick Fix to replace errors with question mark so imports do not fail midway
> replace errors with question mark

- tap_s3_csv/s3.py
Also pr comments
Task: https://varicent.atlassian.net/browse/WP-12009
> WP-12009 fix duplicate rows for file with rows<3

- pyproject.toml
- tap_s3_csv/s3.py
- tap_s3_csv/sync.py
Fix issues when given range is so small that it might not contain any rows.
> Import parallel filesizes

- pyproject.toml
- tap_s3_csv/sync.py
- tap_s3_csv/transform.py
https://varicent.atlassian.net/browse/WP-12914
csv import fails for file in ticket due to null values
> WP-12914 handle null values when source type is specified

- pyproject.toml
- tap_s3_csv/dialect.py
https://varicent.atlassian.net/browse/WP-12916
Default to utf-8 when something goes wrong with encoding detection
> WP-12916 handle encoding detector returning confidence of None

- pyproject.toml
- tap_s3_csv/dialect.py
- assume standard csv dialect when detecting fails
> WP-13288 ignore errors when detecting dialect

- tap_s3_csv/csv_iterator.py
- tap_s3_csv/s3.py
WP-14195 csv import labels Text column as number
https://varicent.atlassian.net/browse/WP-14195
notes: 
- modified sample rate to 1 so that row order does not distort the type inference.
- version update for tag creation included in pr https://github.com/symon-ai/tap-s3-csv/pull/46
> WP-14195 csv import labels Text column as number

- pyproject.toml
- tap_s3_csv/sync.py
https://varicent.atlassian.net/browse/WP-15425
> WP-15425 Use header instead of column_order when it isn't present

- pyproject.toml
- tap_s3_csv/__init__.py
- tap_s3_csv/csv_iterator.py
- tap_s3_csv/preprocess.py
- tap_s3_csv/s3.py
- tap_s3_csv/symon_exception.py
- tap_s3_csv/sync.py
[Import] Improve error handling for S3Csv, AmazonS3
https://varicent.atlassian.net/browse/WP-15503
[Export] Improve error handling for taps
https://varicent.atlassian.net/browse/WP-15969
> WP-15503 [Import] Improve error handling for S3Csv, AmazonS3

- pyproject.toml
- tap_s3_csv/__init__.py
WP-17438 Error handling clean up
https://varicent.atlassian.net/browse/WP-17438
> WP-17438 Error handling clean up

- pyproject.toml
- tap_s3_csv/conversion.py
WP-16421 Imports isn't recognizing booleans
https://varicent.atlassian.net/browse/WP-16421
notes: fix to infer boolean column by case insensitive values
> WP-16421 Imports isn't recognizing booleans

- pyproject.toml
- tap_s3_csv/s3.py
- tap_s3_csv/sync.py
WP-18852 Support import of .txt files
https://varicent.atlassian.net/browse/WP-18852
> WP-18852 Support import of .txt files

- README.md
- pyproject.toml
- tap_s3_csv/__init__.py
- tap_s3_csv/config.py
- tap_s3_csv/csv_iterator.py
- tap_s3_csv/sync.py
allows restricting rows via row_limit param during sync
> WP-20062 add row limit to csv

- pyproject.toml
- tap_s3_csv/sync.py
Task: https://varicent.atlassian.net/browse/WP-19501
Main app pr: https://github.com/symon-ai/app/pull/13796
> WP-19501 SFTP CSV Import - Scalability & Performance

- pyproject.toml
- tap_s3_csv/__init__.py
(write a short description or paste a link to JIRA)
https://varicent.atlassian.net/browse/WP-20360
Need to remove a variable that was added to logs that shouldn't be there
> WP-20360:Increase usage visibility of import and export connectors

- pyproject.toml
- tap_s3_csv/__init__.py
https://varicent.atlassian.net/browse/WP-21444
- added logs to an array to print them as a single log to save space on splunk
> WP-21444: Update splunk logs

- pyproject.toml
- tap_s3_csv/__init__.py
(write a short description or paste a link to JIRA)
- 
- 
- revert this branch
> remove new line character

- pyproject.toml
- tap_s3_csv/dialect.py
(write a short description or paste a link to JIRA)
https://varicent.atlassian.net/browse/WP-24541
Data from file confusing dialect detector. Added additional check and fixes to clean up the data and finally default if needed.
- Import file multiple times from ticket. (Currently it should fail 50% of the time)
- 
- revert this branch
> WP-24541: Import - Unexpected import failure with rba rule file 

- tap_s3_csv/s3.py
- tap_s3_csv/sync.py
Task: https://varicent.atlassian.net/browse/WP-25060
> WP-25060 Support multi part file import for Sales Planning import connector

- pyproject.toml
> WP-25060 increase version - support multi part file import for Sales Planning import connector

- pyproject.toml
- tap_s3_csv/dialect.py
Task: https://varicent.atlassian.net/browse/WP-25220
After Fix:
> WP-25220 fix encoding detection issue where ascii was not assigned as utf-8

- tap_s3_csv/conversion.py
216160 - SCC - Date formatting inconsistency
https://varicent.atlassian.net/browse/WP-27562
notes:
add new format YYYY-MM-DDTHH:MM:SS - this will allow user to keep time values if they want.
> WP-27562 add dateformat with time value
